resolver: lts-14.17
packages:
- .

extra-deps:
- git: https://github.com/ocharles/hlint-source-plugin.git
  commit: d4cded0a7432dc2d5884b9bedd2c714ce510d3ce
  subdirs:
    - plugin
- hlint-2.2.5

allow-newer: true
